[package]
name = "status-slayer"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
signal-hook = "0.3.17"
toml = "0.8.19"

[dev-dependencies]
pretty_assertions = "1.4.1"
rstest = "0.23.0"
